kind: Service
apiVersion: v1
metadata:
  name: php-service
spec:
  selector:
    app: php-test
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-test
  labels:
    app: php-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-test
  template:
    metadata:
      labels:
        app: php-test
    spec:
      imagePullSecrets:
      - name: devops-docker-registry
      containers:
      - name: php-test
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
